StackOverflowOsc.Web/Controllers/AnswersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Antlr.Runtime.Misc;
using AutoMapper;
using StackOverflow.data;
using StackOverflowOsc.Domain.Entities;
using StackOverflowOsc.Web.Models;

namespace StackOverflowOsc.Web.Controllers
{
    [Authorize]
    public class AnswersController : Controller
    {
        public UnitOfWork UnitOfWork = new UnitOfWork();

        private readonly IMappingEngine _mappingEngine;
        public AnswersController(IMappingEngine mappingEngine)
        {
            _mappingEngine = mappingEngine;
        }
        //
        // GET: /Answers/
        public ActionResult Index(Guid questionId)
        {
            var anws = UnitOfWork.QuestionRepository.GetEntityById(questionId);
            List<AnswerListModel> models = new List<AnswerListModel>();
            TimeCalculator calculator = new TimeCalculator();
            Mapper.CreateMap<Answer, AnswerListModel>();
            foreach (Answer a in anws.Answers)
            {
                var answer = Mapper.Map<Answer, AnswerListModel>(a);
                answer.OwnerName = UnitOfWork.AccountRepository.GetEntityById(answer.AccountId).Name;
                answer.LastName = UnitOfWork.AccountRepository.GetEntityById(answer.AccountId).LastName;
                var account = UnitOfWork.AccountRepository.GetEntityById(a.AccountId);
                answer.OwnerName = account.Name;
                answer.Date = calculator.GetTime(a.CreationDate);
                models.Add(answer);
            }
            return View(models);
        }

        public ActionResult CreateAnswer()
        {
            return View(new CreateAnswerModel());
        }

        [HttpPost]
        public ActionResult CreateAnswer(CreateAnswerModel modelAnswer, Guid questionId)
        {
            Mapper.CreateMap<CreateAnswerModel, Answer>().ReverseMap();
            var answer = Mapper.Map<CreateAnswerModel, Answer>(modelAnswer);
            answer.QuestionId = questionId;
            var question = UnitOfWork.QuestionRepository.GetEntityById(questionId);
            question.AnswerCount += 1;

            answer.AccountId = Guid.Parse(HttpContext.User.Identity.Name);
            UnitOfWork.QuestionRepository.Update(question);
            UnitOfWork.AnswerRepository.InsertEntity(answer);
            UnitOfWork.Save();
            return RedirectToAction("Index", "Question");
        }

        [AllowAnonymous]
        public ActionResult ViewAnswer(Guid answerId)
        {
            Mapper.CreateMap<Answer, ShowAnswerModel>();
            var question = UnitOfWork.QuestionRepository.GetEntityById(answerId);
            var owner = UnitOfWork.AccountRepository.GetEntityById(question.Owner);
            var modelAnswer = Mapper.Map<Question, ShowQuestionModel>(question);
            return View(modelAnswer);
        }

        public ActionResult VotePlus(Guid answerId)
        {
            var answer = UnitOfWork.AnswerRepository.GetEntityById(answerId);
            answer.Votes++;
            UnitOfWork.AnswerRepository.Update(answer);
            UnitOfWork.Save();
            return RedirectToAction("ShowQuestion", "Question", new { questionId = answer.QuestionId });
        }

        public ActionResult VoteLess(Guid answerId)
        {
            var answer = UnitOfWork.AnswerRepository.GetEntityById(answerId);
            answer.Votes--;
            UnitOfWork.AnswerRepository.Update(answer);
            UnitOfWork.Save();
            return RedirectToAction("ShowQuestion", "Question", new { questionId = answer.QuestionId });
        }

        public ActionResult IsCorrect(AnswerListModel model)
        {
            var question = UnitOfWork.QuestionRepository.GetEntityById(model.QuestionId);
            var userId = Guid.Parse(HttpContext.User.Identity.Name);
            if (model.AccountId == userId)
            {
                if (model.Correct)
                {
                    question.State = false;
                    UnMark(model);
                }
                else if (!model.Correct)
                {
                    Mark(model);
                    question.State= true;
                }
                UnitOfWork.QuestionRepository.Update(question);
                UnitOfWork.Save();
            }

            return RedirectToAction("ShowQuestion", "Question", new { questionId = model.QuestionId });
        }

        private void Mark(AnswerListModel model)
        {
            Mapper.CreateMap<AnswerListModel, Answer>();
            var answer = Mapper.Map<AnswerListModel, Answer>(model);
            answer.Correct = true;
            UnitOfWork.AnswerRepository.Update(answer);
        }

        private void UnMark(AnswerListModel model)
        {
            Mapper.CreateMap<AnswerListModel, Answer>();
            var answer = Mapper.Map<AnswerListModel, Answer>(model);
            answer.Correct = false;
            UnitOfWork.AnswerRepository.Update(answer);
        }
	}
}

StackOverflowOsc.Web/Controllers/QuestionController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Security.Cryptography;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;
using Antlr.Runtime.Misc;
using AutoMapper;
using StackOverflow.data;
using StackOverflowOsc.Domain.Entities;
using StackOverflowOsc.Web.Models;

namespace StackOverflowOsc.Web.Controllers
{
    [Authorize]
    public class QuestionController : Controller
    {
        private readonly IMappingEngine _mappingEngine;
        public QuestionController(IMappingEngine mappingEngine)
        {
            _mappingEngine = mappingEngine;
        }
        //
        // GET: /Question/
        public UnitOfWork UnitOfWork = new UnitOfWork();
        [AllowAnonymous]
        public ActionResult Index()
        {
            var questions = UnitOfWork.QuestionRepository.Get();
            var models = new List<QuestionListModel>();
            Mapper.CreateMap<Question, QuestionListModel>().ReverseMap();
            TimeCalculator calculator = new TimeCalculator();
            foreach (var q in questions)
            {
                var date = calculator.GetTime(q.CreationDate);
                var model = Mapper.Map<Question, QuestionListModel>(q);
                model.Date = date;
                model.OwnerId = q.Owner;
                model.OwnerName = UnitOfWork.AccountRepository.GetEntityById(model.OwnerId).Name;
                model.LastName = UnitOfWork.AccountRepository.GetEntityById(model.OwnerId).LastName;
                models.Add(model);
            }
            return View(models);
            
        }

        [HttpPost]
        public ActionResult AskQuestion(AskQuestionModel modelQuestion)
        {
            Mapper.CreateMap<AskQuestionModel, Question>().ReverseMap();
            var question = Mapper.Map<AskQuestionModel, Question>(modelQuestion);
            question.Owner = Guid.Parse(HttpContext.User.Identity.Name);
            UnitOfWork.QuestionRepository.InsertEntity(question);
            UnitOfWork.Save();
            return RedirectToAction("Index", "Question");
        }

        public ActionResult AskQuestion()
        {
            return View(new AskQuestionModel());
        }

        [AllowAnonymous]
        public ActionResult ShowQuestion(Guid questionId)
        {
            Mapper.CreateMap<Question, ShowQuestionModel>();
            var question = UnitOfWork.QuestionRepository.GetEntityById(questionId);
            question.Views += 1;
            var owner = UnitOfWork.AccountRepository.GetEntityById(question.Owner);
            var model = Mapper.Map<Question, ShowQuestionModel>(question);
            TimeCalculator calculator = new TimeCalculator();
            string date = calculator.GetTime(question.CreationDate);
            model.Date = date;
            UnitOfWork.QuestionRepository.Update(question);
            UnitOfWork.Save();
            model.OwnerEmail = owner.Email;
            model.Name = owner.Name;
            model.LastName = owner.LastName;
            return View(model);
        }

        public ActionResult VotePlus(Guid questId)
        {
            var ownerId = Guid.Parse(HttpContext.User.Identity.Name);

            var question = UnitOfWork.QuestionRepository.GetEntityById(questId);
            question.Votes += 1;
            UnitOfWork.QuestionRepository.Update(question);
            UnitOfWork.Save();
            return RedirectToAction("ShowQuestion", "Question", new { questionId = questId });
        }

        public ActionResult VoteLess(Guid questId)
        {
            var question = UnitOfWork.QuestionRepository.GetEntityById(questId);
            question.Votes -= 1;
            UnitOfWork.QuestionRepository.Update(question);
            UnitOfWork.Save();
            return RedirectToAction("ShowQuestion", "Question", new { questionId = questId });
        }
    }
}

StackOverflowOsc.Web/Views/Question/AskQuestion.cshtml
@model StackOverflowOsc.Web.Models.AskQuestionModel

@{
    ViewBag.Title = "Ask Question";
}

<h2>AskQuestion</h2>


@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>AskQuestionModel</h4>
        <hr />
        @Html.ValidationSummary(true)

        <div class="form-group">
            @Html.LabelFor(model => model.Title, new {@class = "control-label col-md-2"})
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title)
                @Html.ValidationMessageFor(model => model.Title)
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Description, new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Description)
                @Html.ValidationMessageFor(model => model.Description)
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Search" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
}

StackOverflowOsc.Web/Views/Question/Index.cshtml
@model System.Collections.Generic.IEnumerable<StackOverflowOsc.Web.Models.QuestionListModel>

@{
    ViewBag.Title = "Questions";
}

<head>
    <title>Index</title>
    <style>
        .row {
            width: 100%;
            text-align: center;
        }

        .block {
            width: 50px;
            display: inline-block;
            text-align: center;
            cursor: pointer;
        }
    </style>
</head>

<div>
    <h2 style="display: inline-block">Top Questions</h2>
    <button onclick="window.location.href='/Question/AskQuestion/'" style="display: inline-block; margin-left: 50%" type="button" class="btn btn-warning">Ask Question</button>
</div>
<br />
<hr/>

<ul>
    @foreach (var item in Model)
    {
        <li>
            <div>
                <div class="block" onclick="window.location.href = '/Question/QuestionDetail/?questionId=' + '@item.Id'">
                    <div><span title="@item.Votes votes">@item.Votes</span></div>
                    <div>votes</div>
                </div>
                <div class="block" onclick="window.location.href = '/Question/QuestionDetail/?questionId=' + '@item.Id'">
                    <div class="block"><span title="@item.AnswerCount answers">@item.AnswerCount </span></div>
                    <div>answers</div>
                </div>
                <div class="block" onclick="window.location.href = '/Question/QuestionDetail/?questionId=' + '@item.Id'">
                    <div class="block"><span title="@item.Views views">@item.Views</span></div>
                    <div>views</div>
                </div>
                <blockquote style="display: inline-block">
                    @Html.ActionLink(@item.Title, "ShowQuestion", "Question", new { questionId = item.Id }, null)
                    <footer>
                        Asked @item.Date ago by
                        @Html.ActionLink(@item.OwnerName + " " + @item.LastName, "Profile", "Account", new { ownerId = item.OwnerId }, null)
                    </footer>
                </blockquote>
            </div>
        </li>
    }
</ul>

StackOverflowOsc.Web/Views/Question/ShowQuestion.cshtml
@model StackOverflowOsc.Web.Models.ShowQuestionModel

@{
    ViewBag.Title = "ShowQuestion";
}

<h3>@Model.Title</h3>

<div>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @using (Html.BeginForm("VotePlus", "Question", new { questId = Model.Id }))
            {
                <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-thumbs-up"></span></button>
            }
            <label style="text-align: center; margin-left: 65%">@Model.Votes </label>
            @using (Html.BeginForm("VoteLess", "Question", new { questId = Model.Id }))
            {
                <button class="btn btn-xs btn-default"><span class="glyphicon glyphicon-thumbs-down"></span></button>
            }
            <br />
        </dt>
        <dd>
            <h4>@Model.Description</h4>
        </dd>
    </dl>
    <div style="margin-left: 25%; background-color: sienna; width: 200px;">
        Asked @Model.Date
        <br />by
        @Html.ActionLink(Model.Name + " " + Model.LastName, "Profile", "Account", new { ownerId = Model.OwnerId }, null)
        <br />
        Views @Model.Views
    </div>
</div>
<div>
    @{Html.RenderAction("Index", "Answers", new { models = Model.Answers });}
</div>
<p>
    @Html.ActionLink("Answer Question", "CreateAnswer", "Answers",new { questionId = Model.Id }, null)
</p>